name: PostgreSQL Backup to Azure Blob Storage


on:
   push:
    branches: [ "main" ]
jobs:
  postgres_backup_prod:
    name: Take backup of postgres database in prod
    env:
      POSTGRES_PROD_PASSWORD: ${{ secrets.PASSWORD }}
      POSTGRES_BACKUP_FILENAME: BACKUP$(date +'%Y-%m-%d')


    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install psycopg2-binary azure-storage-blob

      - name: Take PostgreSQL backup
        run: |
          PGPASSWORD=$POSTGRES_PROD_PASSWORD pg_dumpall -U postgres -h 20.207.72.66 -p 5432 -v -f ${{ env.POSTGRES_BACKUP_FILENAME }}

      - name: Compress the backup file into a tar
        run: |
          tar -cvzf ${{ env.POSTGRES_BACKUP_FILENAME }}.tar.gz ${{ env.POSTGRES_BACKUP_FILENAME }}

      - name: Store PostgreSQL backup to Azure Blob Storage
        run: |
          azcopy copy ${{ env.POSTGRES_BACKUP_FILENAME }}.tar.gz "${{secrets.AZURE_CONTAINER_URL}}/${{secrets.CONTAINERNAME}}/${{ env.POSTGRES_BACKUP_FILENAME }}.tar.gz${{secrets.SASTOKEN}}"
     

    
