name: backup
on:
   push:
    branches: [ "main" ]
jobs:
  postgres:
    name: backup for postgres
    env:
      POSTGRES_PROD_PASSWORD: ${{ secrets.PASSWORD }}
      POSTGRES_BACKUP_FILENAME: BACKUP$(date +'%Y-%m-%d')


    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install azure-storage-blob
        run: |
          pip install psycopg2-binary azure-storage-blob

      - name: Taking backup
        run: |
          PGPASSWORD=$POSTGRES_PROD_PASSWORD pg_dumpall -U postgres -h 20.207.72.66 -p 5432 -v -f ${{ env.POSTGRES_BACKUP_FILENAME }}

      - name: Compress file into a tar
        run: |
          tar -cvzf ${{ env.POSTGRES_BACKUP_FILENAME }}.tar.gz ${{ env.POSTGRES_BACKUP_FILENAME }}

      - name: Store backup to Blob Storage
        run: |
          azcopy copy ${{ env.POSTGRES_BACKUP_FILENAME }}.tar.gz "${{secrets.AZURE_CONTAINER_URL}}/${{secrets.CONTAINERNAME}}/${{ env.POSTGRES_BACKUP_FILENAME }}.tar.gz${{secrets.SASTOKEN}}"
 
  mongodb:
    name: backup for mongodb
    env:
      
      MONGODB_PROD_PASSWORD: ${{secrets.MPASSWORD}}
      MONGODB_BACKUP_FILENAME: backup$(date +'%Y-%m-%d').archive
     

    runs-on: ubuntu-latest

    steps:

      - name: Install Mongodb
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 656408E390CFB1F5
          echo "deb http://repo.mongodb.org/apt/ubuntu $(lsb_release -sc)/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
          sudo apt-get update
          sudo apt-get install -y mongodb-database-tools

      - name: Taking backup
        run: |
          mongodump --host 20.207.72.66 --port 27017 --authenticationDatabase=admin --username myAdmin --password $MONGODB_PROD_PASSWORD --archive=${{ env.MONGODB_BACKUP_FILENAME }}

      - name: Store backup to Blob Storage
        run: |
          azcopy copy ${{ env.MONGODB_BACKUP_FILENAME }} "${{secrets.CONTAINER_URI}}/mongobackup/${{ env.MONGODB_BACKUP_FILENAME }}${{secrets.MSASTOKEN}}"

 

    
