name: PostgreSQL Backup to Azure Blob Storage

on:
   push:
    branches: [ "main" ]
  

env:
  AZURE_SAS_TOKEN: ${{ secrets.SASTOKEN }} 

jobs:

  postgres_backup_prod:
    name: Take backup of postgres database in prod
    env:
      POSTGRES_PROD_HOST: 20.207.72.66
      POSTGRES_PROD_USER: postgres
      POSTGRES_PROD_PORT: 5432
      POSTGRES_PROD_PASSWORD: ${{ secrets.PASSWORD }}
      POSTGRES_BACKUP_FILENAME: backupfile$(date +'%Y-%m-%d')
      CONTAINER_URI: ${{ secrets.AZURE_CONTAINER_URL }}
      CONTAINER_NAME: ${{ secrets.CONTAINERNAME }}

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install psycopg2-binary azure-storage-blob

      - name: Take PostgreSQL backup
        run: |
          PGPASSWORD=$POSTGRES_PROD_PASSWORD pg_dumpall -U $POSTGRES_PROD_USER -h $POSTGRES_PROD_HOST -p $POSTGRES_PROD_PORT -v -f ${{ env.POSTGRES_BACKUP_FILENAME }}

      - name: Compress the backup file into a tar
        run: |
          tar -cvzf ${{ env.POSTGRES_BACKUP_FILENAME }}.tar.gz ${{ env.POSTGRES_BACKUP_FILENAME }}

      - name: Store PostgreSQL backup to Azure Blob Storage
        run: |
          azcopy copy ${{ env.POSTGRES_BACKUP_FILENAME }}.tar.gz "${{ env.CONTAINER_URI }}/${{ env.CONTAINER_NAME }}/${{ env.POSTGRES_BACKUP_FILENAME }}.tar.gz${{ env.AZURE_SAS_TOKEN}}"
     

    
